export default [
	{
		question: "The infiltration team drops you off down the street from the hotel. You walk a few minutes and arrive. Before you lies the vast lobby of a ritzy hotel -- this is the one, alright. Now it’s just a matter of getting to Dr. Disinfo’s room. First, you need to figure out which penthouse suite belongs to him.",
		answers: ["> Threaten the concierge into telling you where Dr. Disinfo’s suite is.", "> Find a quiet corner and contact your team back at base.", "> Hack into the hotel’s database.", "> Offer a bellhop a bribe to let it slip."],
        messages: ["You nonchalantly arrive at the concierge and reveal your stun gun from behind your coat. “Where’s your boss?” you say coldly. She pales. “He’s on the top floor, all the way down the hall. Is there, uh, anything else I can do for you?” she blurts out, not wanting to provoke you to act on your threat. You tell her not to mention your conversation, and you make your way to the elevator.", "Using your handy dandy communication watch, you ask your team if they managed to pinpoint Disinfo’s location while you were en route. Turns out, the promising new intern did! “Yep I did boss! He’s staying in the most private room: the penthouse suite on the far end of the hall on the top floor. Take the elevator up and head down the hall all the way. You got this Agent!” You end the call and head for the elevator.", "You take out your specially modified smart phone and log into the hotel’s high-speed internet. After going through a digital backdoor into their database, you access the-- frankly, not very well protected-- directory. Skimming through, you quickly find Disinfo’s entry; looks like he’s staying in the penthouse suite furthest down the hall on the top floor.", "“Where’s your boss?” you say slyly to the bellhop and flash a crisp $100 bill. The young bellhop’s eyes widen at the sight of the bill. He eagerly tells you that he took Disinfo’s suspiciously bulky bags up to the penthouse suite just the other day. It’s at the end of the hall on the top floor. You thank the bellhop, hand him the promised money, and go on your way."]
	},
	{
        question: "You summon the elevator and with a DING the doors open. You walk in. Just as the doors are closing a shifty looking guy in a trenchcoat squeezes in. Who wears a trenchcoat in sunny Los Angeles? As the elevator rises he tries to make small talk. How do you respond?",
		answers:  ["> Put earbuds in and stare down at your phone, acting as though you hadn’t heard him.", "> Give a polite, generic response.", "> Glare at him coldly until he gets the message that you don’t want to talk.", "> Subtly drop a hint about pineapple on pizza and watch for a reaction."],
		messages: ["He repeats his question. When you continue not to respond he glares at you, sighs, and straightens his coat.", "The two of you spend a good thirty seconds chatting about the weather. You really don’t want to be having this conversation, but it’s important you remain as unremarkable as possible.", "He looks at you uncomfortably. “Alright then,” he mutters under his breath. Easy as pie.", "At the mention of pineapple on pizza you see him recoil. It was a movement so small that the average person wouldn’t have noticed, even if they were looking for it. He recovers quickly and says, “Ah, I’ve uh always found it to be a silly thing to put on pizza. Not quite my thing. Always thought it might make me sick.” Something’s not quite right here."]
	},
	{
		question: "The man reaches into his jacket pocket. You hear a quiet click, and the elevator grinds to a halt. You were so close to the top floor! The doors are locked shut. Turns out you were right to be on the lookout for Dr. Disinfo’s minions. He takes off his coat revealing a Dr. Disinfo henchmen uniform underneath. He readies a defensive stance. What do you do?",
		answers: ["> Push the “doors open” button and to get out of here quick as you can.","> Use your stun gun to incapacitate the henchman and use his remote to restart the elevator.","> Break the light in the ceiling, then take advantage of the darkness to climb through the hatch and out.","> He doesn't seem like such a tough guy. You can take him."],
		messages: ["You slam the button and the doors open, the top floor a few feet above the threshold of the elevator. You dive through the gap and roll to your feet. The hallway is crawling with guards to the right. To the left all the way down the hall you see a door left ajar. The Penthouse! You race for the door and the guards take chase. You enter to find this is no ordinary penthouse. It's a secret lair. In the middle of the room you see your worst nightmare: a giant pizza shaped rocket, poised to annihilate the entire city. The guards rush in and surround you. WHAM! You're smacked in the head and blackout.","You stun him before he can do anything and the guard falls to the floor. You take the remote from him, it’s shaped like a little pizza slice. You press the “pepperoni” button, and the elevator doors open to the top floor. The hallway is crawling with guards to the right. To the left all the way down the hall you see a door left ajar. The Penthouse! You race for the door and the guards take chase. You enter to find this is no ordinary penthouse; It's a secret lair. In the middle of the room you see your worst nightmare: a giant pizza shaped rocket, poised to annihilate an entire city. The guards rush in and surround you. WHAM! You're smacked in the head and blackout.","With a single well-placed punch, the plastic light shatters and the light flickers off. The minion lunges blindly for you, but it’s too late. You’re already scrambling up through the emergency hatch of the elevator and emerge into the dim shaft. You pry open the door to the top floor and emerge in the hallway. The hallway is crawling with guards to the right. To the left all the way down the hall you see a door left ajar. The Penthouse! You race for the door and the guards take chase. You enter to find this is no ordinary penthouse; It's a secret lair. In the middle of the room you see your worst nightmare: a giant pizza shaped rocket, poised to annihilate an entire city. The guards rush in and surround you. WHAM! You're smacked in the head and blackout.","You raise your fists and with a single well place uppercut, he’s out like a light. You take the remote from him. It’s shaped like a little pizza slice. You press the “pepperoni” button, and the elevator doors open to the top floor. The hallway is crawling with guards to the right. To the left all the way down the hall you see a door left ajar. The Penthouse! You race for the door and the guards take chase. You enter to find this is no ordinary penthouse; It's a secret lair. In the middle of the room you see your worst nightmare: a giant pizza shaped rocket, poised to annihilate an entire city. The guards rush in and surround you. WHAM! You're smacked in the head and blackout."]
	},
	{
		question: "You feel a bright light shining on you as you slowly wake. You’re strapped down to an operating table. A figure emerges from the darkness, clapping slowly. Doctor Disinfo. “Ah, I knew it was only a matter before you showed up agent. For, you see, I am unstoppable! My plans foolproof! My looks… very handsome.” How do you respond?",
		answers: ["> “Please sir, I don't know anything! I was just here to deliver a pizza!”", "> Remain silent. He’ll never break you.", "> Flash your most seductive smile.", "> Spit at him."],
		messages: ["He doesn’t believe you. He’s your nemesis. You’ve fought countless times. In retrospect, that was kind of a silly tactic. Nevertheless, you tell him that someone at this hotel room ordered a pepperoni with extra cheese and you need someone to sign for it. Disinfo finds this ridiculous, but nonetheless he leaves the room to check if any of his minions ordered a pizza.","“Very well, agent. I see we will need to do this the difficult way.” Intimidated, he leaves the room to find some guards as backup.","He raises an eyebrow. “You know, agent, despite all the times you’ve stopped me I always thought we had a chance.” You bat your eyelashes coyly. He smiles and rushes out to grab a bottle of wine he’s been saving.","Disgusted, he spits back at you and misses. Pathetic. He leaves the room in search of a towel."]
	},
	{
		question: "Now’s your opportunity to escape! You’ve got some options.",
		answers: ["> Strain against your bonds. Surely your bulging biceps are strong enough to break them!","> Reflect on the poor choices that brought you into this situation.","> Survey the room for something to help you escape.","> Activate the tiny hidden explosive in the heel of your shoe. These are drastic times…"],
		messages: ["With a mighty tug you break the leather straps! Freedom at last!", "In your contemplation, you realize that the restraints are slightly too big for your slim wrists. With a little work, you manage to weasel your hands free. A moment later, your legs are free too.", "Your eyes fall upon a very attractive classy pen only a centimeters from your hand. Pens rock! You reach for it and manage to pick the lock on your bonds with the pointy tip.", "You realize this is actually an extremely reckless idea and will result in you blowing off your foot. Panicking, you kick the device free and send it sailing into the air. It lands on a computer control panel. A few seconds later, it explodes. With the destruction of the computer system, your restraints pop open."]
	},
	{
        question: "As soon as your feet touch the ground, an alarm blares. Dr. Disinfo will surely return soon!",
		answers: ["> Hide behind the door. They’ll never find you there.","> Put up your dukes, they’ll never take you alive!","> Get back on the table and pretend you’re still a captive.","> Start screaming."],
		messages: ["You stand behind the door in your perfect hiding place. Several minutes go by and nothing happens. Just as you begin to feel foolish, the door swings open, and Disinfo with two guards rush in. The first place they check is behind the door. Darn. You swing the door back in their faces and SLAP! The door knocks them all to their feet unconscious.", "After a few moments, Disinfo and two guards burst in. Upon seeing you, they stop cold, sizing you up. Disinfo knows this look in your eyes. He says to the guards, “don’t you dare underestimate--” Just as fast as you lift your hands up, their bodies fall to the ground, defeated by your furious flurry of fists. You're good. You're real good.", "After a few moments, Disinfo and two guards burst in. They slowly approach the table, eyeing you. When they get close, you leap up! Unfortunately, the guards shove you back. You recover and size them up. You stare them down and just as fast as you lift your fists up, the bodies of these goons fall to the ground defeated by your furious flurry of fists. You're good, you're really good.", "When Disinfo and two guards arrive, they find you screaming at the top of your lungs. Even when they approach you, you continue bellowing out a primal sound that could wake the dead. Finally the air in your lungs runs out and you’re forced to take a breath. Before the guards can rush you, your windpipes explode with volume, and they all run out of the room clutching their ears."]
	},
	{
		question: "You leave the room and search for the rocket. You find it, and see a screen running diagnostics in front of it. Below the screen you see several levers, wires, a large red button and many blinking lights. How are you going to disable this rocket?",
		answers: [ "> Access the location system and reconfigure the launch path to hit an empty spot in the ocean.", "> Press the large red button on the control panel.", "> Grab a pair of pliers and cut the power source to the control panel.", "> Decide that the control panel isn’t worth your time and start hitting the rocket’s blasters instead."],
		messages: ["Your fingers fly deftly over the controls, typing in coordinates in the center of the Pacific. The realization that you’re about to sentence thousands, perhaps millions, of marine creatures to a watery pizza grave flashes through your mind. However, like a leaf in the breeze, it soon flits away as you spot a colorful blinking light. A robotic voice echoes over the PA system. “Rocket implosion imminent.” Whoopsies.", "Your hand hovers over the button and you hesitate and examine the situation. It’s a large red button. Deciding that’s reason enough, you slam your fist down. It feels great. A robotic voice echoes over the PA system. “Rocket implosion imminent.” That part doesn’t feel so great.", "As one hand grabs the pliers from their wall mounting, the other reaches for the cord connecting the control panel to the wall. As you pull the cord towards you, the plug is yanked out of the wall and the panel shuts off. Well that was easy. You cut the wires anyways for good measure. A robotic voice echoes over the PA system, “Rocket implosion imminent.” Oops.", "You pound your fists against the metal of the rocket. After several minutes you stop to examine your progress. Upon discovering that you haven’t even scratched the paint, you take a wrench and begin to hit the rocket with that. Finally, the battered metal gives and you admire the lovely hole you’ve made. A robotic voice echoes over the PA system. “Rocket implosion imminent.” Looks like you might’ve gone a bit too far this time."]
	},
	{
		question: "You leave the penthouse and enter the hallway. Everything has gone crazy. Everyone must’ve heard the rocket is going to implode. Scientists, technicians, henchmen, all running like chickens with their heads cut off are scrambling for the nearest escape. You've got to get downstairs ASAP. Scanning your environment you see a couple options:",
		answers: ["> You see a vent system that probably runs through the whole hotel. Crawl in and make your way through the air conditioning system.", "> There’s an exterior window just down the hall. Bust out the window and rappel down the side of the building.", "> There’s what appears to be an elevator with a plaque on it, reading: DR. DISINFO’S PRIVATE ESCAPE ROUTE, DON’T USE UNLESS YOU’RE DR. DISINFO. Looks like it might be the express option for you!", "> Jump out the window in your suit's backup parachute."],
		messages: ["As you pry open the grate of the air duct cool wind washes over you. It's about to get chilly. You climb in on your stomach, crawling, your arms tucked in front of you. After a short time you come to the main shaft that runs vertically down the whole building. A service ladder runs all the way up and down. you climb all the way down to the ground floor vent. Carefully prying it open you emerge.", "CRASH! Glass shatters at your feet. You hook up your rappel line, tying it off to the window frame. Just as you’re about to drop down, a guard stops. She stares at you, cocking her head to the side, confused. You raise you index finger to your lips. “Shhhhh”. You wink and disappear out the window.", "With a smirk you press the button and the doors whoosh open. You’re greeted by a small pod with a strap in chair and two buttons: down or up. You lock in and press the down button. The doors begin to close and just as they do Dr. Disinfo appears through the crowd. “HEY-” he manages to yelp before the doors shut. The pod drops and you feel your stomach lurch. Within seconds the door opens to the hotel lobby.", "You run at the window and jump at it smashing through. It only hurts a little. You begin to freefall. As the ground quickly approaches you pull the cord at your waist and a parachute opens, allowing you to gently float to the ground."]
	},
	{
		question: "You make it to exterior of the hotel where there are plenty of vehicles by the curb each with a Dr. Disinfo insignia. Quick! Which one will become your new getaway vehicle?",
		answers: [ "> A slick matte black Aston Martin, presumably belonging to Dr. Disinfo", "> A van filled with all the tech you could ever need!", "> A dashing red convertible with chrome highlights", "> A low profile Prius"],
		messages: ["Trying to pull open the door, you find it, surprise, locked. “I’m sorry,” you whimper as you brace your elbow and smash through the glass. Climbing through the window you sit in the driver’s seat, pop open the dashboard below the steering wheel, and connect the two red wires, hotwiring the car.", "What a find! You didn’t know you’d be finding the coolest car ever on this mission! You climb in the driver’s seat and look behind you to see the trunk of the van is adorned with screens of all sizes, each flooded with lines of code, technical readouts, maps, graphs, apps… its a techno dream. You pop open the dashboard below the steering wheel and connect the two red wires, hotwiring the van.", "With the grace of an fennec fox you slide across the hood of the car and hop into the driver’s seat. You pop open the dashboard below the steering wheel and connect the two red wires, hotwiring the car.", "Ah yes, the mark of a true agent: the most unassuming and nondescript car imaginable. You get in the Prius and sit at the wheel. You pop open the dashboard below the steering wheel and connect the two red wires, hotwiring the car."]
	},
	{
		question: "In your rearview mirror you see Dr. Disinfo burst through the doors of the hotel. Furious, he launches himself onto the vehicle, clinging to the hood. Looking at the steering wheel you see a shiny red button right in the center. Dr. Disinfo screams “DONT YOU DARE DO IT!” You don't know what it does. Do you press it?",
		answers: ["> Yes", "> No"],
		messages: ["With your most winning smirk you look straight at Dr. Disinfo and press the button. A rumble. You can feel the vehicle transforming around you. “NO!” Dr. Disinfo screams, holding ever tighter to the hood. Wings slide out on either side of the car. The wheels fold in, locking into position position as the vehicle rises off the ground just a few inches. You floor it. Dr. Disinfo, grasping for any kind of hold on the hood slides off and falls to the ground. You pull back on the steering wheel and the car lifts higher off the ground, the urban sprawl far below you. Dr. Disinfo picks himself up and shakes his fist violently at you as he sees nothing but a speck on the horizon fading into the crimson sunset.", "You smirk at Dr. Disinfo and slam on the gas. Your vehicle screeches out of the hotel valet with all the roar the engine can muster. Swerving left and right to shake him off, you narrowly avoid oncoming traffic. Bit by bit he’s slipping off. One last swerve should do it… one final tug of the steering wheel and Dr. Disinfo is hanging on by his fingertips. “This is just the beginning.” He says just before falling off the hood. and rolls across the ground. Dr. Disinfo picks himself up and shakes his fist violently at you as he sees nothing but a speck on the horizon fading into the crimson sunset."]
	}

]

